//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAIL
    {
        public int ORDER_DETAIL_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
