//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.CARTDETAILs = new HashSet<CARTDETAIL>();
            this.COMMENTs = new HashSet<COMMENT>();
            this.FAVORITEs = new HashSet<FAVORITE>();
            this.FEATUREs = new HashSet<FEATURE>();
            this.RATINGs = new HashSet<RATING>();
        }
    
        public int PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string COLOR { get; set; }
        public string PRODUCT_IMAGE { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
        public Nullable<int> PRODUCT_COUNT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> PRODUCER_ID { get; set; }
        public Nullable<int> PRODUCTTYPE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTDETAIL> CARTDETAILs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVORITE> FAVORITEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEATURE> FEATUREs { get; set; }
        public virtual PRODUCER PRODUCER { get; set; }
        public virtual PRODUCTTYPE PRODUCTTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATING> RATINGs { get; set; }
    }
}
